"""Public entry points for the standalone Atlas ERP foundation."""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .connect_server import (
        ConnectHandler,
        ConnectServer,
        sale_command_hash,
        snapshot_cursor,
        wire_manifest,
    )

from .business import (
    AuditSnapshot,
    CASH_ACCOUNT,
    CASH_ACCOUNT_CODE,
    Business,
    BusinessError,
    DuplicateItemError,
    DuplicateJournalError,
    DuplicateOrderError,
    DuplicateReceiptError,
    DuplicateSaleError,
    InvalidJournalEntryError,
    InvalidOrderError,
    InvalidPriceError,
    InvalidQuantityError,
    InvalidSaleError,
    InsufficientStockError,
    JOURNAL_ACCOUNT_CODES,
    JournalEntry,
    JournalLine,
    MasterItem,
    PurchaseOrder,
    PurchaseOrderLine,
    REVENUE_ACCOUNT,
    REVENUE_ACCOUNT_CODE,
    Receipt,
    Sale,
    SaleLine,
    StockLevel,
    StockMovement,
    UnbalancedJournalEntryError,
    UnknownItemError,
    UnknownJournalError,
    UnknownOrderError,
    UnknownReceiptError,
    UnknownSaleError,
    register_business_capabilities,
)
from .business_store import (
    BusinessRecords,
    BusinessStore,
    InMemoryBusinessStore,
    PostgresBusinessStore,
)
from .protocol import (
    CONNECT_VERSION,
    AuthorityConflictError,
    ConnectProtocol,
    Delta,
    IncompatibleVersionError,
    InMemoryAdapter,
    InMemoryProtocolAdapter,
    InvalidCursorError,
    PermissionDeniedError,
    Proposal,
    ProposalError,
    ProtocolError,
    ProtocolKernel,
    Snapshot,
    compatible_version,
    handshake,
    validate_authorities,
)
from .registry import (
    BASELINE_CLUSTERS,
    DEFAULT_APP_ID,
    DEFAULT_CONNECT_VERSION,
    DuplicateRegistrationError,
    Registry,
    RegistryError,
    UnknownRegistrationError,
)
from .sale_store import (
    IN_PROGRESS,
    PAYLOAD_CONFLICT,
    REPLAY,
    RESERVED,
    InMemorySaleCommandStore,
    PostgresSaleCommandStore,
    SaleCommandError,
    SaleCommandReservation,
    SaleCommandStore,
)

__all__ = [
    "AuditSnapshot",
    "AuthorityConflictError",
    "BASELINE_CLUSTERS",
    "Business",
    "BusinessError",
    "BusinessRecords",
    "BusinessStore",
    "CASH_ACCOUNT",
    "CASH_ACCOUNT_CODE",
    "CONNECT_VERSION",
    "ConnectHandler",
    "ConnectProtocol",
    "ConnectServer",
    "DEFAULT_APP_ID",
    "DEFAULT_CONNECT_VERSION",
    "Delta",
    "DuplicateItemError",
    "DuplicateJournalError",
    "DuplicateOrderError",
    "DuplicateReceiptError",
    "DuplicateRegistrationError",
    "DuplicateSaleError",
    "IncompatibleVersionError",
    "InMemoryBusinessStore",
    "InMemorySaleCommandStore",
    "IN_PROGRESS",
    "InvalidCursorError",
    "InvalidJournalEntryError",
    "InvalidOrderError",
    "InvalidPriceError",
    "InvalidQuantityError",
    "InvalidSaleError",
    "InsufficientStockError",
    "JOURNAL_ACCOUNT_CODES",
    "JournalEntry",
    "JournalLine",
    "MasterItem",
    "PAYLOAD_CONFLICT",
    "PermissionDeniedError",
    "PostgresBusinessStore",
    "PostgresSaleCommandStore",
    "Proposal",
    "ProposalError",
    "ProtocolError",
    "ProtocolKernel",
    "PurchaseOrder",
    "PurchaseOrderLine",
    "REPLAY",
    "RESERVED",
    "REVENUE_ACCOUNT",
    "REVENUE_ACCOUNT_CODE",
    "Receipt",
    "Registry",
    "RegistryError",
    "Sale",
    "SaleCommandError",
    "SaleCommandReservation",
    "SaleCommandStore",
    "SaleLine",
    "Snapshot",
    "StockLevel",
    "StockMovement",
    "UnbalancedJournalEntryError",
    "UnknownItemError",
    "UnknownJournalError",
    "UnknownOrderError",
    "UnknownReceiptError",
    "UnknownRegistrationError",
    "UnknownSaleError",
    "compatible_version",
    "register_business_capabilities",
    "handshake",
    "sale_command_hash",
    "snapshot_cursor",
    "validate_authorities",
    "wire_manifest",
]


def __getattr__(name: str) -> object:
    if name in {
        "ConnectHandler",
        "ConnectServer",
        "sale_command_hash",
        "snapshot_cursor",
        "wire_manifest",
    }:
        from .connect_server import (
            ConnectHandler,
            ConnectServer,
            sale_command_hash,
            snapshot_cursor,
            wire_manifest,
        )

        return {
            "ConnectHandler": ConnectHandler,
            "ConnectServer": ConnectServer,
            "sale_command_hash": sale_command_hash,
            "snapshot_cursor": snapshot_cursor,
            "wire_manifest": wire_manifest,
        }[name]
    raise AttributeError(name)
